// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizLand.Infrastructure.Persistance.SQl;

#nullable disable

namespace QuizLand.Infrastructure.Persistance.SQl.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizLand.Domain.Models.Avatars.Avatar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Avatars", (string)null);
                });

            modelBuilder.Entity("QuizLand.Domain.Models.CodeLogs.CodeLogs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Device")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SendedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodeLogs");
                });

            modelBuilder.Entity("QuizLand.Domain.Models.Courses.Course", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("QuizLand.Domain.Models.Gamers.Gamer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Gamers", (string)null);
                });

            modelBuilder.Entity("QuizLand.Domain.Models.Games.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CountOfJoinedClients")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MatchClients")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid?>("WinnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WinnerUserId");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("QuizLand.Domain.Models.Questions.Question", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CorrectOption")
                        .HasColumnType("int");

                    b.Property<long?>("CountClickFirstOption")
                        .HasColumnType("bigint");

                    b.Property<long?>("CountClickFourthOption")
                        .HasColumnType("bigint");

                    b.Property<long?>("CountClickSecondOption")
                        .HasColumnType("bigint");

                    b.Property<long?>("CountClickThirdOption")
                        .HasColumnType("bigint");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<string>("DescriptiveAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FourthOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Question", (string)null);
                });

            modelBuilder.Entity("QuizLand.Domain.Models.RandQuestionAnswers.RoundQuestionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GamerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<long>("RoundQuestionId")
                        .HasColumnType("bigint");

                    b.Property<int>("SelectedOption")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GamerId");

                    b.HasIndex("RoundQuestionId");

                    b.ToTable("RoundQuestionAnswers", (string)null);
                });

            modelBuilder.Entity("QuizLand.Domain.Models.RandQuestions.RoundQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("int");

                    b.Property<long>("RoundId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("RoundId");

                    b.ToTable("RoundQuestions", (string)null);
                });

            modelBuilder.Entity("QuizLand.Domain.Models.Rands.Round", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FirstAnswerGamerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("FirstRandQuestionId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<int>("RoundStatus")
                        .HasColumnType("int");

                    b.Property<long?>("SecondRandQuestionId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SelectingGamerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ThirdRandQuestionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("FirstAnswerGamerId");

                    b.HasIndex("FirstRandQuestionId");

                    b.HasIndex("GameId");

                    b.HasIndex("SecondRandQuestionId");

                    b.HasIndex("SelectingGamerId");

                    b.HasIndex("ThirdRandQuestionId");

                    b.ToTable("Rounds", (string)null);
                });

            modelBuilder.Entity("QuizLand.Domain.Models.Supporters.Supporter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsBan")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Supporters", (string)null);
                });

            modelBuilder.Entity("QuizLand.Domain.Models.TicketMessages.TicketMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSupporter")
                        .HasColumnType("bit");

                    b.Property<long?>("ReplyTo")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("SenderSupporterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SenderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("Ticketid")
                        .HasColumnType("bigint");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReplyTo");

                    b.HasIndex("SenderSupporterId");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("Ticketid");

                    b.ToTable("TicketMessages", (string)null);
                });

            modelBuilder.Entity("QuizLand.Domain.Models.Tickets.Ticket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AssigneeSupporterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeSupporterId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("QuizLand.Domain.Models.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActiveDeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("AvatarId")
                        .HasColumnType("bigint");

                    b.Property<long>("Coin")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBan")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Level")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TokenVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("XP")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("QuizLand.Domain.Models.Gamers.Gamer", b =>
                {
                    b.HasOne("QuizLand.Domain.Models.Games.Game", "Game")
                        .WithMany("Gamers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuizLand.Domain.Models.Users.User", "User")
                        .WithMany("Gamers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuizLand.Domain.Models.Games.Game", b =>
                {
                    b.HasOne("QuizLand.Domain.Models.Users.User", "Winner")
                        .WithMany("Games")
                        .HasForeignKey("WinnerUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("QuizLand.Domain.Models.Questions.Question", b =>
                {
                    b.HasOne("QuizLand.Domain.Models.Courses.Course", "Course")
                        .WithMany("Questions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("QuizLand.Domain.Models.RandQuestionAnswers.RoundQuestionAnswer", b =>
                {
                    b.HasOne("QuizLand.Domain.Models.Gamers.Gamer", "Gamer")
                        .WithMany("RoundQuestionAnswers")
                        .HasForeignKey("GamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizLand.Domain.Models.RandQuestions.RoundQuestion", "RoundQuestion")
                        .WithMany("RoundQuestionAnswers")
                        .HasForeignKey("RoundQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gamer");

                    b.Navigation("RoundQuestion");
                });

            modelBuilder.Entity("QuizLand.Domain.Models.RandQuestions.RoundQuestion", b =>
                {
                    b.HasOne("QuizLand.Domain.Models.Questions.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizLand.Domain.Models.Rands.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("QuizLand.Domain.Models.Rands.Round", b =>
                {
                    b.HasOne("QuizLand.Domain.Models.Courses.Course", "Course")
                        .WithMany("Rounds")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuizLand.Domain.Models.Gamers.Gamer", "FirstAnswerGamer")
                        .WithMany()
                        .HasForeignKey("FirstAnswerGamerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuizLand.Domain.Models.RandQuestions.RoundQuestion", "FirstRoundQuestion")
                        .WithMany()
                        .HasForeignKey("FirstRandQuestionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuizLand.Domain.Models.Games.Game", "Game")
                        .WithMany("Rounds")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuizLand.Domain.Models.RandQuestions.RoundQuestion", "SecondRoundQuestion")
                        .WithMany()
                        .HasForeignKey("SecondRandQuestionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuizLand.Domain.Models.Gamers.Gamer", "Gamer")
                        .WithMany()
                        .HasForeignKey("SelectingGamerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuizLand.Domain.Models.RandQuestions.RoundQuestion", "ThirdRoundQuestion")
                        .WithMany()
                        .HasForeignKey("ThirdRandQuestionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Course");

                    b.Navigation("FirstAnswerGamer");

                    b.Navigation("FirstRoundQuestion");

                    b.Navigation("Game");

                    b.Navigation("Gamer");

                    b.Navigation("SecondRoundQuestion");

                    b.Navigation("ThirdRoundQuestion");
                });

            modelBuilder.Entity("QuizLand.Domain.Models.TicketMessages.TicketMessage", b =>
                {
                    b.HasOne("QuizLand.Domain.Models.TicketMessages.TicketMessage", null)
                        .WithMany()
                        .HasForeignKey("ReplyTo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuizLand.Domain.Models.Supporters.Supporter", "SenderSupporter")
                        .WithMany("TicketMessages")
                        .HasForeignKey("SenderSupporterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuizLand.Domain.Models.Users.User", "SenderUser")
                        .WithMany("TicketMessages")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuizLand.Domain.Models.Tickets.Ticket", "Ticket")
                        .WithMany("TicketMessages")
                        .HasForeignKey("Ticketid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SenderSupporter");

                    b.Navigation("SenderUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("QuizLand.Domain.Models.Tickets.Ticket", b =>
                {
                    b.HasOne("QuizLand.Domain.Models.Supporters.Supporter", "Supporter")
                        .WithMany("Tickets")
                        .HasForeignKey("AssigneeSupporterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuizLand.Domain.Models.Users.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Supporter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuizLand.Domain.Models.Users.User", b =>
                {
                    b.HasOne("QuizLand.Domain.Models.Avatars.Avatar", "Avatar")
                        .WithMany("Users")
                        .HasForeignKey("AvatarId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("QuizLand.Domain.Models.Avatars.Avatar", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("QuizLand.Domain.Models.Courses.Course", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("QuizLand.Domain.Models.Gamers.Gamer", b =>
                {
                    b.Navigation("RoundQuestionAnswers");
                });

            modelBuilder.Entity("QuizLand.Domain.Models.Games.Game", b =>
                {
                    b.Navigation("Gamers");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("QuizLand.Domain.Models.RandQuestions.RoundQuestion", b =>
                {
                    b.Navigation("RoundQuestionAnswers");
                });

            modelBuilder.Entity("QuizLand.Domain.Models.Supporters.Supporter", b =>
                {
                    b.Navigation("TicketMessages");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("QuizLand.Domain.Models.Tickets.Ticket", b =>
                {
                    b.Navigation("TicketMessages");
                });

            modelBuilder.Entity("QuizLand.Domain.Models.Users.User", b =>
                {
                    b.Navigation("Gamers");

                    b.Navigation("Games");

                    b.Navigation("TicketMessages");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
